### PR TITLE
Improve testing

### LINKED ISSUE #1357: Rebuild `test_economy_1`
In a way that makes it less error-prone and monolithic, separating the relevant test objectives into a series of different individual test files

### LINKED ISSUE #2007: Oregon rebate test is incredibly slow, somewhat volatile
This test should probably be rewritten to be more sustainable, if not dropped altogether

### LINKED ISSUE #2013: Reorganize `python` testing folder into a `unit` and `integration` folder and begin to increase coverage by file
I'm not yet sure how we should treat the current breakdown we have into `python` and `api` tests, as the `python` tests use standard Pytest, while the `api` tests are built against a YAML parsing structure just to test endpoint liveness and more basic request types - perhaps we even just keep the two separate. Even so, we should do something to break `python` down into `unit`, for file-level unit testing, and `integration`, for cross-API integration testing that doesn't need to correspond with our file structure. This should help increase coverage, as it will be easy to determine what is and isn't tested.

### LINKED ISSUE #2015: Add basic integration testing for UK and US models
The UK tests will likely need some sort of skip statement, since they will fail on local machines that don't have the microdata token

### PR DESCRIPTION
**Pull request by anth-volk**
Fixes #2015 
Partially fixes #2013 (some tests will need to be broken up into relevant files)
Fixes #2007 
Fixes #1357

Inspired by #2010 (a regression introduced by #2006), this PR creates a new testing structure for economy-wide simulations. The aim is to make it simple to test that a series of common reform impacts (e.g., modifying the federal income tax rate) still runs and returns values within reason for certain key measures. This does not compare outputs with country packages (that's open as #2017, but it's unclear if its likely slow pace would justify writing it). 

This also begins to move toward a more concise testing folder structure, whereby integration tests (any that hit use the `rest_client` Pytest fixture to simulate an endpoint hit, then check its response) are distinct from unit tests. A few tests are either also being modified in an open PR or would need to be subdivided to match the internal file structure, so they've been relegated to a temporary `to_be_refactored` folder.

### CODE REVIEW

**Comment by anth-volk** [comment]
Popping this into draft to do some further refactoring on existing tests. I don't like how much exposure our tests have to the local database.

**Review by nikhilwoodruff — APPROVED** [review]
This looks like an improvement to me. But could we at least try using the `subsample` feature to reduce the test runtimes? We've jumped quite a bit to 15m, and I don't think it would reduce accuracy if we're just testing large bounds.

**Comment by anth-volk** [comment]
Per discussion with @nikhilwoodruff, I'll be cutting a few tests out of this later today. Also need to rebase.

**Comment by anth-volk** [comment]
Dropping in favor of a smaller, more tactical testing improvement before expanding coverage.

**Pull request closed without merging**
