### PR TITLE
Americanize country agnostic code

### LINKED ISSUE #1543: Americanize country-agnostic code
For example:

https://github.com/PolicyEngine/policyengine-api/blob/312da084ab3cc4aa5eaced1219bde79d913ede99/policyengine_api/endpoints/economy/compare.py#L24

### PR DESCRIPTION
**Pull request by tawandamoyo**
Partially fixes #1543

### CODE REVIEW

**Comment by anth-volk** [comment]
@tawandamoyo Unfortunately, there are quite a few points in the front end where the output of this API route is utilized, and they all refer to a "labour_supply_impact" or something similar. Would you be willing to Americanize those, as well? Otherwise, these changes will just crash on the front end.

**Comment by tawandamoyo** [comment]
@anth-volk , sure will open a PR for the frontend

**Comment by anth-volk** [comment]
@tawandamoyo Just updated this to deal with some merge conflicts on the API. After tests are run, I believe this will be good to merge, followed by the corresponding front-end fixes. Thanks for your patience.

**Review by anth-volk — APPROVED** [review]
Thanks for this @tawandamoyo! Before merging, https://github.com/PolicyEngine/policyengine-app/pull/2149/files will need to be reviewed and approved. Then we'll merge this, followed by that one.

**Pull request merged**
