### PR TITLE
Fix typo in README.md: Remove repeated word

### PR DESCRIPTION
**Pull request by tawandamoyo**
Removed the repeated word "anything" in the README.

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for this PR, @tawandamoyo, and apologies for the lack of update on this.

When making commits to the PR, we require (as laid out in our README) that contributors
- Run a linter
- Contribute to our changelog, so that we can track what changes were made when

Could you refer to the README, starting at https://github.com/PolicyEngine/policyengine-api?tab=readme-ov-file#step-2-formatting, and do that? Then we should be able to get this merged!

**Comment by tawandamoyo** [comment]
Thanks for the feedback @anth-volk , making the changes.

**Comment by anth-volk** [comment]
Thanks again for this @tawandamoyo.

Unfortunately, there are a couple issues with the PR. The first is that we've updated since this was opened, which throws off the changelog system, requiring rebasing. 

The second is that for the API, we actually require contributors to clone, not fork, and then we add them manually as contributors. This is because of some sensitive elements that we cannot pass along to contributors. I hate to ask this, but could you clone the repo and reopen this? If so, I'll add you as a contributor.

Clearly (ironically), we need to update our README on this. I've opened it at https://github.com/PolicyEngine/policyengine-api/issues/1648.

**Comment by tawandamoyo** [comment]
It's alright, thanks @anth-volk , have cloned again. Ready to reopen.

**Pull request closed without merging**
