### PR TITLE
Add .yaml extension to test_get_search_malformed_country_id

### LINKED ISSUE #447: Add .yaml extension to tests/api/test_get_search_malformed_country_id
https://github.com/PolicyEngine/policyengine-api/blob/master/tests/api/test_get_search_malformed_country_id

### PR DESCRIPTION
**Pull request by anth-volk**
Adding .yaml extension to test_get_search_malformed_country_id, which previously had no file extension. Fixes #447.

### CODE REVIEW

**Comment by anth-volk** [comment]
This PR fails because of a separate bug in get_search whereby a query-less search crashes instead of returning 404. I'll repair that separately, then fix the .yaml extension bug in a commit of a series of tests that I've been working on that not only fixes the .yaml extension issue, but also adds more tests, names them more succinctly, etc.

**Comment by anth-volk** [comment]
Instead of trying to address the 500 issue and closing the failed PR, I've altered the test to provide a search query, then will separately address the 500 errors in a separate PR

**Comment by MaxGhenis** [comment]
Could you try updating your branch again to get rid of the unnecessary diffs?

**Comment by anth-volk** [comment]
Will do, thanks for the heads-up

**Review by nikhilwoodruff — APPROVED** [review]
Sorry for my delay in getting to this- LGTM!

**Pull request merged**
