### PR TITLE
Rename endpoints to use hyphens not underscores

### LINKED ISSUE #1863: Rename endpoints containing underscores to use hyphens
I believe this includes "user_policy", "user_profile", and "liveness_check"

### PR DESCRIPTION
**Pull request by tawandamoyo**
Fixes #1863 

## requires

- [x] frontend update of edited endpoints - pr opened at [#2123](https://github.com/PolicyEngine/policyengine-app/pull/2123)

### CODE REVIEW

**Comment by anth-volk** [comment]
Just quickly, could you change "Targeting" to "Fixes," either now or when you convert out of draft? "Targeting" actually doesn't close any issues.

**Comment by anth-volk** [comment]
And just to check: were you also willing to open a PR with the required changes on the front end?

**Comment by tawandamoyo** [comment]
> And just to check: were you also willing to open a PR with the required changes on the front end?

Yes. Opened [issue 2122](https://github.com/PolicyEngine/policyengine-app/issues/2122)

**Comment by anth-volk** [comment]
Considering the significance of these changes, I'm going to wait to review/merge until very late Monday for a couple reasons:

* Two of these require a bit of reconfiguration on Google Cloud to ensure we do liveness checks properly
* There's always a chance that we miss some front-end fetch change, thereby temporarily breaking things

**Review by anth-volk — CHANGES_REQUESTED** [review]
Thanks for your work on this @tawandamoyo. Before pushing, I wanted to check to see how this would impact our Google Cloud deployment, and I think this would crash our health checks. Following the documentation [here](https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=python#liveness_checks), could you update `gcp/policyengine_api/app.yaml` to utilize the new readiness and liveness check URLs? I think you'd only need to update the `path` value.

**Comment by tawandamoyo** [comment]
fixed, thanks

**Review by anth-volk — APPROVED** [review]
Thank you @tawandamoyo! I believe this is ready to merge. I will hold off merging your other breaking changes (the ones that Americanize) until Sunday so that we can be doubly sure nothing breaks as a result of these.

**Pull request merged**
