### PR TITLE
Increase max GCP instances to 2

### PR DESCRIPTION
**Pull request by anth-volk**
ISSUE TO BE ADDED. This is a draft PR that would increase the max number of GCP instances to 2.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Seems worth trying this, but can we check what triggers it? Does a single microsim get us to 80% CPU? I think we'd ideally spin up when there's a queue.

@nikhilwoodruff also suggested checking on the queue display. I'd suggest not making that a blocker though.

**Comment by MaxGhenis** [comment]
I'm going to merge this in case it might help with an active project, which involves many LSR simulations.

**Comment by anth-volk** [comment]
If this doesn't end up spinning up new instances, we could also consider dropping the target utilization rate

**Comment by MaxGhenis** [comment]
Merging this caused an API error soni reverted

**Comment by anth-volk** [comment]
Weird, let me dig into this a bit

**Pull request merged**
